version: "3"
services:
  backend-api:
    build:
      context: ./backend.api
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    container_name: backend-api
    volumes:
      - ./backend.api:/app/backend-api
  frontend-app:
    build:
      context: ./frontend.app
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    container_name: frontend-app
    stdin_open: true
    volumes:
      - ./frontend.app:/app/frontend-app
      - /app/frontend-app/node_modules
      - /app/frontend-app/.next
  frontend-website:
    build:
      context: ./frontend.website
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3080:3080"
    container_name: frontend-website
    stdin_open: true
    volumes:
      - ./frontend.website:/app/frontend-website
      - /app/frontend-website/node_modules
      - /app/frontend-website/.next
