version: "3"
services:
  backend-api:
    build:
      context: ./Backend.Api
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    container_name: backend-api
    volumes:
      - ./Backend.Api:/app/backend-api
  frontend-app:
    build:
      context: ./Frontend.WebApp
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    container_name: frontend-app
    stdin_open: true
    volumes:
      - ./Frontend.WebApp:/app/frontend-app
      - /app/frontend-app/node_modules
      - /app/frontend-app/.next
  frontend-website:
    build:
      context: ./Frontend.Website
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    container_name: frontend-website
    stdin_open: true
    volumes:
      - ./Frontend.Website:/app/frontend-website
      - /app/frontend-website/node_modules
      - /app/frontend-website/.next
