version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3080:3080"
    container_name: backend
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
