version: "3"
services:
  backend:
    build:
      context: ./Vision.Backend
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    container_name: backend
    volumes:
      - ./Vision.Backend:/usr/src/app/Vision.Backend
  frontend:
    build:
      context: ./Vision.Frontend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    container_name: frontend
    stdin_open: true
    volumes:
      - ./Vision.Frontend:/usr/src/app/Vision.Frontend
      - /usr/src/app/Vision.Frontend/node_modules
      - /usr/src/app/Vision.Frontend/.next
